{"name": "test_002_for_edge_cases[input1]", "status": "broken", "statusDetails": {"message": "TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'", "trace": "self = <Test.test_001.Test_001 object at 0x0000026764B92560>, input = {'dateofbirth': '2100-02-26', 'unit': 'day'}\n\n    @pytest.mark.parametrize(\"input\", d['edge_case_data'])\n    def test_002_for_edge_cases(self, input):\n>       self.clientUtil.verify_valid_data(params={\n                                        \"dateofbirth\": input['dateofbirth'],\n                                        \"unit\": input['unit']\n                                        })\nE       TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'\n\nTest\\test_001.py:19: TypeError"}, "parameters": [{"name": "input", "value": "{'dateofbirth': '2100-02-26', 'unit': 'day'}"}], "start": 1685017518697, "stop": 1685017518697, "uuid": "a409b201-b0a6-493c-b8ff-7be63d8f7eda", "historyId": "d924273fac9f9ad1418838d49c11425b", "testCaseId": "347cc2d951f0f58d7452c7de6ca19a62", "fullName": "Test.test_001.Test_001#test_002_for_edge_cases", "labels": [{"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "DESKTOP-FEG7QCL"}, {"name": "thread", "value": "8016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_001"}]}