{"name": "test_002_for_edge_cases[input2]", "status": "broken", "statusDetails": {"message": "TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'", "trace": "self = <Test.test_001.Test_001 object at 0x0000026764B925F0>, input = {'dateofbirth': '2000-02-29', 'unit': 'day'}\n\n    @pytest.mark.parametrize(\"input\", d['edge_case_data'])\n    def test_002_for_edge_cases(self, input):\n>       self.clientUtil.verify_valid_data(params={\n                                        \"dateofbirth\": input['dateofbirth'],\n                                        \"unit\": input['unit']\n                                        })\nE       TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'\n\nTest\\test_001.py:19: TypeError"}, "parameters": [{"name": "input", "value": "{'dateofbirth': '2000-02-29', 'unit': 'day'}"}], "start": 1685017518709, "stop": 1685017518709, "uuid": "aad49ae3-dd02-4426-a6bd-a262c32bb60e", "historyId": "187d7a535e3a6eabd88793e0000b7041", "testCaseId": "347cc2d951f0f58d7452c7de6ca19a62", "fullName": "Test.test_001.Test_001#test_002_for_edge_cases", "labels": [{"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "DESKTOP-FEG7QCL"}, {"name": "thread", "value": "8016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_001"}]}