{"name": "test_002_for_edge_cases[input0]", "status": "broken", "statusDetails": {"message": "TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'", "trace": "self = <Test.test_001.Test_001 object at 0x00000154786ED570>, input = {'dateofbirth': '1900-02-26', 'unit': 'day'}\n\n    @pytest.mark.parametrize(\"input\", d['edge_case_data'])\n    def test_002_for_edge_cases(self, input):\n>       self.clientUtil.verify_valid_data(params={\n                                        \"dateofbirth\": input['dateofbirth'],\n                                        \"unit\": input['unit']\n                                        })\nE       TypeError: Client.verify_valid_data() got an unexpected keyword argument 'params'\n\nTest\\test_001.py:19: TypeError"}, "parameters": [{"name": "input", "value": "{'dateofbirth': '1900-02-26', 'unit': 'day'}"}], "start": 1685017228124, "stop": 1685017228125, "uuid": "0f6c2bd7-4fa7-4058-a303-11b420195ef1", "historyId": "e21fadcd7f53f7940db17bb507a2445a", "testCaseId": "347cc2d951f0f58d7452c7de6ca19a62", "fullName": "Test.test_001.Test_001#test_002_for_edge_cases", "labels": [{"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_001"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "DESKTOP-FEG7QCL"}, {"name": "thread", "value": "3360-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_001"}]}